version: "3.9"
services:
    orderbook:
        build: .
        restart: on-failure:3
        networks:
            - clickhouse_default
    aggtrade:
        build:
            context: .
            dockerfile: dockerfile-aggtrade
        restart: on-failure:3
        networks:
            - clickhouse_default
networks:
  clickhouse_default:
    external: true