version: "3"
services:
    clickhouse:
        image: yandex/clickhouse-server
        volumes:
            - ./database:/var/lib/clickhouse
        ulimits: 
            nofile:
                soft: 262144
                hard: 262144
        ports:
            - "8123:8123"
            - "9000:9000"
        restart: always