version: "3"
services:
    orderbook:
        build: .
        restart: always
    aggtrade:
        build:
            context: .
            dockerfile: dockerfile-aggtrade
        restart: always